/** All user-facing text lives here: warm, never guilt-based. Easy to localize later. */
export const copy = {
  appName: 'Bloom',
  startCta: 'Start focusing',
  streak: (n: number) => (n === 1 ? '1 day streak' : `${n} day streak`),
  streakZero: 'Your streak starts today',
  totalMinutes: (m: number) => `${m.toLocaleString()} min grown`,
  toNext: (m: number, name: string) => `${m.toLocaleString()} min until ${name}`,
  fullyGrown: 'Fully grown — and still growing with you',
  pickDuration: 'How long would you like to focus?',
  custom: 'Custom',
  minutesUnit: 'min',
  labelPlaceholder: 'What are you focusing on? (optional)',
  begin: 'Begin',
  back: 'Back',
  running: ['Growing quietly…', 'Soaking up the light…', 'Roots getting deeper…', 'Doing great, keep going.'],
  paused: 'Paused while you were away. Welcome back.',
  resumedAfterReload: 'Paused — pick up whenever you’re ready.',
  resume: 'Resume',
  endEarly: 'End session',
  confirmEnd: 'End now? Every minute you focused still counts.',
  doneTitle: 'Well done',
  earlyTitle: 'Nice work',
  doneBody: (m: number) => `${m} focused minutes. Your companion soaked that in.`,
  shortBody: 'A short one — sessions of 5+ minutes help your companion grow. Stopping by still matters.',
  stageUp: (name: string) => `Your companion grew into a ${name}!`,
  home: 'Back home',
  clearData: 'Clear my data',
  confirmClear: 'This permanently deletes your companion and history from this device. Continue?',
  privacy: 'Everything stays on this device. No accounts, no tracking.',
};
